/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FullscreenRouteImport } from './routes/fullscreen'
import { Route as VisualizerRouteImport } from './routes/visualizer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FullscreenRoute = FullscreenRouteImport.update({
  id: '/fullscreen',
  path: '/fullscreen',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizerRoute = VisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fullscreen': typeof FullscreenRoute
  '/visualizer': typeof VisualizerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fullscreen': typeof FullscreenRoute
  '/visualizer': typeof VisualizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fullscreen': typeof FullscreenRoute
  '/visualizer': typeof VisualizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fullscreen' | '/visualizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fullscreen' | '/visualizer'
  id: '__root__' | '/' | '/fullscreen' | '/visualizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FullscreenRoute: typeof FullscreenRoute
  VisualizerRoute: typeof VisualizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fullscreen': {
      id: '/fullscreen'
      path: '/fullscreen'
      fullPath: '/fullscreen'
      preLoaderRoute: typeof FullscreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualizer': {
      id: '/visualizer'
      path: '/visualizer'
      fullPath: '/visualizer'
      preLoaderRoute: typeof VisualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FullscreenRoute: FullscreenRoute,
  VisualizerRoute: VisualizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
